import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);									//number of trails
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		   					
	int Two = 0;												//families with 2 children
	int Three = 0; 											//families with 3 children
	int Four = 0;												//families with 4 children or more
	double sum = 0;												//for caculating the average
		
															//The paste part from OneOfEachStats
			for (int j = 0; j<T; j++){							//loop for T times
		double randomNumber1 = generator.nextDouble(); 		//generate random number
		boolean checkboy = false;									//0-4 for boy 5-9 for girl
		boolean checkgirl = false;
		if(randomNumber1 >= 0.5)
		checkgirl= true;			
		else
			checkboy=true;	
		int i = 1;
			while (checkboy == false || checkgirl == false){
			randomNumber1 = generator.nextDouble();;
			if (randomNumber1 < 0.5){
			checkboy = true;
			i++;
			}
				else;
				if (randomNumber1 >= 0.5) {
				checkgirl=true;
				i++;
					}
					else;														//end of paste part from OneOfEachStats
				}
				if(i==2)
					Two++;
				if(i==3)
					Three++;
				if(i>=4)
					Four++;
				sum=sum+i;
			}			
double Average= sum/T;															//loop ends
	System.out.println("Average: "+Average+" children to get at least one of each gender.");				
	System.out.println("Number of families with 2 children: "+Two);
	System.out.println("Number of families with 3 children: "+Three);
	System.out.println("Number of families with 4 or more children: "+Four);
	if(Two>=Three&&Two>=Four)
	System.out.println("The most common number of children is 2.");								//the IF's checking which number-
	if(Three>Two&&Three>=Four)																	//- of children is the most common
	System.out.println("The most common number of children is 3.");
	if(Four>Two&&Four>Three)
	System.out.println("The most common number of children is 4 or more.");
	}
}
